<?php
/**
 * Copyright © Magmodules.eu. All rights reserved.
 * See COPYING.txt for license details.
 *
 * @var $block Magmodules\Reloadify\Block\Adminhtml\Magmodules\Header
 */
?>
<div class="magmodules-reloadify-header">
    <div class="">
        <p class="magmodules-reloadify-header-text">
            <strong>Reloadify for Magento.</strong> Email Marketing for Ecommerce.<br>
            Send personal emails to build strong relationships with customers, create brand experiences, and drive
            repeat purchases. Communicate widely, but talk to each customer on a personal level.<br>
            <span class="development">Developed by <a href="https://www.magmodules.eu/" target="_blank">Magmodules</a>.
            </span>
        </p>
    </div>
    <div class="magmodules-reloadify-header-actions">
        <a id="magmodules-reloadify-button_help" class="helpbutton"
           href="<?= $block->escapeUrl($block->getSupportLink()); ?>"
           target="_blank">
            <i class="magmodules-reloadify-icon__question-circled"></i>
            <span><?= $block->escapeUrl(__('Support')); ?></span>
        </a>
        <button id="magmodules-reloadify-button_test" title="<?= $block->escapeUrl(__('Run Self-test')); ?>"
                type="button" class="action-default scalable">
            <i class="magmodules-reloadify-icon__list-unordered-four"></i>
            <span><?= $block->escapeUrl(__('Self-test')); ?></span>
        </button>
    </div>
</div>
